### PR TITLE
Auth tweaks

### PR DESCRIPTION
**Pull request by darrenleeweber**
A few tweaks to the authentication and authorization code, to simplify validations and correct response codes.  Adapted while developing an authentication protocol for the triannon-client (work in progress).

### CODE REVIEW

**Comment by darrenleeweber** [comment]
Requesting review of these tweaks from @ndushay, @azaroth42 and/or @cbeer

**Comment by azaroth42** [comment]
(finger on nose ... not the right person to review code at this level)

**Comment by darrenleeweber** [comment]
Mainly curious about feedback from @cbeer and @ndushay on consolidating the response/rendering handlers in the access validation methods.  The previous code had response handling in several methods and this revision attempts to consolidate it into the validation, where all the logic to authentication and/or authorize access resides and the logic for 401 vs. 403 responses is clear.  However, this is my initial work on an auth API and I'm wondering whether there are any problems in the current approach that might be solved with better patterns.

**Comment by darrenleeweber** [comment]
@azaroth42 was included to check the json response data for 401 vs. 403 and perhaps to consider and/or discuss any recent developments in the IIIF auth workflow that might apply here (or generate tickets for triannon).

**Comment by ndushay** [comment]
I sorta skimmed this and nothing jumps out at me.  It looks like you decided to change from a 302 in one context to a 200 -- this may affect the code I did in Searchworks.  Perhaps the spec could be clarified and documented with @azaroth42 :  when we get which response codes for each http request that is part of authenization handshake.

**Comment by azaroth42** [comment]
It shouldn't matter, as the response from login is ignored in our
scenario.  It never goes to the user, and the client doesn't get any
information back.  In the future, it should be a 200 with javascript that
tries to close the window.

R

**Comment by darrenleeweber** [comment]
This is as good as it can be now, unless we have to change response code specs.  The change from a 302 to a 200 response was a result of reconsidering an HTML vs. JSON interaction and the latter JSON pattern works better with 200 rather than a more conventional 302 redirect in HTML patterns.  @ndushay - I think we can merge this and deploy to triannon-dev today.

**Comment by darrenleeweber** [comment]
I'll address documentation in the next PR.

**Pull request merged**
