### PR TITLE
revise Gemfile per engine_cart v0.6.0

### PR DESCRIPTION
**Pull request by ndushay**
@darrenleeweber  per discussion w @azaroth42 

FYI, I also did a PR on engine_cart itself so the comments I added will be added by engine_cart in the future.  (https://github.com/cbeer/engine_cart/pull/24)

### CODE REVIEW

**Comment by darrenleeweber** [comment]
Travis failed the PR, maybe it's missing a VCR file?  Otherwise it looks OK.

**Comment by ndushay** [comment]
travis pages also implied we could get faster throughput with the change I just made to .travis.yml.

http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade

(thanks for the catch on the vcr cassettes)

**Comment by darrenleeweber** [comment]
Neat, looks good to go; merging it.

**Comment by azaroth42** [comment]
Thanks Naomi, Darren :)

On Thu, Jul 9, 2015 at 4:17 PM, Darren L. Weber, Ph.D. <
notifications@github.com> wrote:

> Neat, looks good to go; merging it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sul-dlss/triannon/pull/212#issuecomment-120172445>.
>



-- 
Rob Sanderson
Information Standards Advocate
Digital Library Systems and Services
Stanford, CA 94305

**Pull request merged**
